start-process ".\target\release\alphas.exe" -ArgumentList "-n 2 -a 2 -u 1000000 -m 10000000 -f strict --inner-angle"  -WorkingDirectory "D:\anl_nuke\faust_anl"
start-process ".\target\release\alphas.exe" -ArgumentList "-n 2 -a 2 -u 1000000 -m 10000000 -f strict --inner-angle --mixer std --skip-real --det-filter none"  -WorkingDirectory "D:\anl_nuke\faust_anl"
start-process ".\target\release\alphas.exe" -ArgumentList "-n 2 -a 2 -u 1000000 -m 10000000 -f strict --inner-angle --mixer std --skip-real --det-filter faust"  -WorkingDirectory "D:\anl_nuke\faust_anl"
start-process ".\target\release\alphas.exe" -ArgumentList "-n 2 -a 2 -u 1000000 -m 10000000 -f strict --inner-angle --mixer std --skip-real --det-filter 1"  -WorkingDirectory "D:\anl_nuke\faust_anl"
start-process ".\target\release\alphas.exe" -ArgumentList "-n 2 -a 2 -u 1000000 -m 10000000 -f strict --inner-angle --mixer std --skip-real --det-filter 4"  -WorkingDirectory "D:\anl_nuke\faust_anl"
start-process ".\target\release\alphas.exe" -ArgumentList "-n 2 -a 2 -u 1000000 -m 10000000 -f strict --inner-angle --mixer std --skip-real --det-filter 8"  -WorkingDirectory "D:\anl_nuke\faust_anl"
start-process ".\target\release\alphas.exe" -ArgumentList "-n 2 -a 2 -u 1000000 -m 10000000 -f strict --inner-angle --mixer phi --skip-real --det-filter none"  -WorkingDirectory "D:\anl_nuke\faust_anl"
start-process ".\target\release\alphas.exe" -ArgumentList "-n 2 -a 2 -u 1000000 -m 10000000 -f strict --inner-angle --mixer phi --skip-real --det-filter faust"  -WorkingDirectory "D:\anl_nuke\faust_anl"
start-process ".\target\release\alphas.exe" -ArgumentList "-n 2 -a 2 -u 1000000 -m 10000000 -f strict --inner-angle --mixer phi --skip-real --det-filter 1"  -WorkingDirectory "D:\anl_nuke\faust_anl"
start-process ".\target\release\alphas.exe" -ArgumentList "-n 2 -a 2 -u 1000000 -m 10000000 -f strict --inner-angle --mixer phi --skip-real --det-filter 4"  -WorkingDirectory "D:\anl_nuke\faust_anl"
start-process ".\target\release\alphas.exe" -ArgumentList "-n 2 -a 2 -u 1000000 -m 10000000 -f strict --inner-angle --mixer phi --skip-real --det-filter 8"  -WorkingDirectory "D:\anl_nuke\faust_anl"

start-process ".\target\release\alphas.exe" -ArgumentList "-n 2 -a 2 -u 1000000 -m 10000000 -f min --inner-angle"  -WorkingDirectory "D:\anl_nuke\faust_anl"
start-process ".\target\release\alphas.exe" -ArgumentList "-n 2 -a 2 -u 1000000 -m 10000000 -f min --inner-angle --mixer std --skip-real --det-filter none"  -WorkingDirectory "D:\anl_nuke\faust_anl"
start-process ".\target\release\alphas.exe" -ArgumentList "-n 2 -a 2 -u 1000000 -m 10000000 -f min --inner-angle --mixer std --skip-real --det-filter faust"  -WorkingDirectory "D:\anl_nuke\faust_anl"
start-process ".\target\release\alphas.exe" -ArgumentList "-n 2 -a 2 -u 1000000 -m 10000000 -f min --inner-angle --mixer std --skip-real --det-filter 1"  -WorkingDirectory "D:\anl_nuke\faust_anl"
start-process ".\target\release\alphas.exe" -ArgumentList "-n 2 -a 2 -u 1000000 -m 10000000 -f min --inner-angle --mixer std --skip-real --det-filter 4"  -WorkingDirectory "D:\anl_nuke\faust_anl"
start-process ".\target\release\alphas.exe" -ArgumentList "-n 2 -a 2 -u 1000000 -m 10000000 -f min --inner-angle --mixer std --skip-real --det-filter 8"  -WorkingDirectory "D:\anl_nuke\faust_anl"
start-process ".\target\release\alphas.exe" -ArgumentList "-n 2 -a 2 -u 1000000 -m 10000000 -f min --inner-angle --mixer phi --skip-real --det-filter none"  -WorkingDirectory "D:\anl_nuke\faust_anl"
start-process ".\target\release\alphas.exe" -ArgumentList "-n 2 -a 2 -u 1000000 -m 10000000 -f min --inner-angle --mixer phi --skip-real --det-filter faust"  -WorkingDirectory "D:\anl_nuke\faust_anl"
start-process ".\target\release\alphas.exe" -ArgumentList "-n 2 -a 2 -u 1000000 -m 10000000 -f min --inner-angle --mixer phi --skip-real --det-filter 1"  -WorkingDirectory "D:\anl_nuke\faust_anl"
start-process ".\target\release\alphas.exe" -ArgumentList "-n 2 -a 2 -u 1000000 -m 10000000 -f min --inner-angle --mixer phi --skip-real --det-filter 4"  -WorkingDirectory "D:\anl_nuke\faust_anl"
start-process ".\target\release\alphas.exe" -ArgumentList "-n 2 -a 2 -u 1000000 -m 10000000 -f min --inner-angle --mixer phi --skip-real --det-filter 8"  -WorkingDirectory "D:\anl_nuke\faust_anl"
