#start-process ".\target\release\alphas.exe" -ArgumentList "-n 3 -a 3 -u 1000000 -m 100000000 -f strict --inner-angle"  -WorkingDirectory "D:\anl_nuke\faust_anl"
#start-process ".\target\release\alphas.exe" -ArgumentList "-n 3 -a 3 -u 1000000 -m 100000000 -f strict --inner-angle --mixer std --skip-real --det-filter none"  -workingdirectory "d:\anl_nuke\faust_anl"
#start-process ".\target\release\alphas.exe" -argumentlist "-n 3 -a 3 -u 1000000 -m 100000000 -f strict --inner-angle --mixer std --skip-real --det-filter faust"  -workingdirectory "d:\anl_nuke\faust_anl"
#start-process ".\target\release\alphas.exe" -argumentlist "-n 3 -a 3 -u 1000000 -m 100000000 -f strict --inner-angle --mixer std --skip-real --det-filter 1"  -workingdirectory "d:\anl_nuke\faust_anl"
#start-process ".\target\release\alphas.exe" -argumentlist "-n 3 -a 3 -u 1000000 -m 100000000 -f strict --inner-angle --mixer std --skip-real --det-filter 4"  -workingdirectory "d:\anl_nuke\faust_anl"
#start-process ".\target\release\alphas.exe" -argumentlist "-n 3 -a 3 -u 1000000 -m 100000000 -f strict --inner-angle --mixer std --skip-real --det-filter 8"  -workingdirectory "d:\anl_nuke\faust_anl"
#start-process ".\target\release\alphas.exe" -argumentlist "-n 3 -a 3 -u 1000000 -m 100000000 -f strict --inner-angle --mixer phi --skip-real --det-filter none"  -workingdirectory "d:\anl_nuke\faust_anl"
#start-process ".\target\release\alphas.exe" -argumentlist "-n 3 -a 3 -u 1000000 -m 10000000 -f strict --inner-angle --mixer phi --skip-real --det-filter faust"  -workingdirectory "d:\anl_nuke\faust_anl"
#start-process ".\target\release\alphas.exe" -argumentlist "-n 3 -a 3 -u 1000000 -m 100000000 -f strict --inner-angle --mixer phi --skip-real --det-filter 1"  -workingdirectory "d:\anl_nuke\faust_anl"
#start-process ".\target\release\alphas.exe" -argumentlist "-n 3 -a 3 -u 1000000 -m 100000000 -f strict --inner-angle --mixer phi --skip-real --det-filter 4"  -workingdirectory "d:\anl_nuke\faust_anl"
#start-process ".\target\release\alphas.exe" -argumentlist "-n 3 -a 3 -u 1000000 -m 100000000 -f strict --inner-angle --mixer phi --skip-real --det-filter 8"  -workingdirectory "d:\anl_nuke\faust_anl"
#start-process ".\target\release\alphas.exe" -argumentlist "-n 3 -a 3 -u 1000000 -m 100000000 -f min --inner-angle"  -workingdirectory "d:\anl_nuke\faust_anl"
#start-process ".\target\release\alphas.exe" -argumentlist "-n 3 -a 3 -u 1000000 -m 100000000 -f min --inner-angle --mixer std --skip-real --det-filter none"  -workingdirectory "d:\anl_nuke\faust_anl"
#start-process ".\target\release\alphas.exe" -argumentlist "-n 3 -a 3 -u 1000000 -m 100000000 -f min --inner-angle --mixer std --skip-real --det-filter faust"  -workingdirectory "d:\anl_nuke\faust_anl"
#start-process ".\target\release\alphas.exe" -argumentlist "-n 3 -a 3 -u 1000000 -m 100000000 -f min --inner-angle --mixer std --skip-real --det-filter 1"  -workingdirectory "d:\anl_nuke\faust_anl"
#start-process ".\target\release\alphas.exe" -argumentlist "-n 3 -a 3 -u 1000000 -m 100000000 -f min --inner-angle --mixer std --skip-real --det-filter 4"  -workingdirectory "d:\anl_nuke\faust_anl"
#start-process ".\target\release\alphas.exe" -argumentlist "-n 3 -a 3 -u 1000000 -m 100000000 -f min --inner-angle --mixer std --skip-real --det-filter 8"  -workingdirectory "d:\anl_nuke\faust_anl"
#start-process ".\target\release\alphas.exe" -argumentlist "-n 3 -a 3 -u 1000000 -m 100000000 -f min --inner-angle --mixer phi --skip-real --det-filter none"  -workingdirectory "d:\anl_nuke\faust_anl"
#start-process ".\target\release\alphas.exe" -argumentlist "-n 3 -a 3 -u 1000000 -m 10000000 -f min --inner-angle --mixer phi --skip-real --det-filter faust"  -workingdirectory "d:\anl_nuke\faust_anl"
#start-process ".\target\release\alphas.exe" -argumentlist "-n 3 -a 3 -u 1000000 -m 100000000 -f min --inner-angle --mixer phi --skip-real --det-filter 1"  -workingdirectory "d:\anl_nuke\faust_anl"
#start-process ".\target\release\alphas.exe" -argumentlist "-n 3 -a 3 -u 1000000 -m 100000000 -f min --inner-angle --mixer phi --skip-real --det-filter 4"  -workingdirectory "d:\anl_nuke\faust_anl"
#start-process ".\target\release\alphas.exe" -argumentlist "-n 3 -a 3 -u 1000000 -m 100000000 -f min --inner-angle --mixer phi --skip-real --det-filter 8"  -WorkingDirectory "D:\anl_nuke\faust_anl"

#start-process ".\target\release\alphas.exe" -argumentlist "-n 3 -a 3 -u 1000000 -m 100000000 -f min --inner-angle --mixer sh_phi --skip-real"  -WorkingDirectory "D:\anl_nuke\faust_anl"
#start-process ".\target\release\alphas.exe" -argumentlist "-n 3 -a 3 -u 1000000 -m 10000000 -f strict --inner-angle --mixer sh_phi --skip-real"  -WorkingDirectory "D:\anl_nuke\faust_anl"
start-process ".\target\release\alphas.exe" -argumentlist "-n 3 -a 3 -u 1000000 -m 1000000 -f min --inner-angle --mixer std --skip-real --det-filter 3"  -workingdirectory "d:\anl_nuke\faust_anl"
